### ISSUE TITLE
Any Support for discriminator-based multi-tenancy?

### ISSUE THREAD

**Issue by pengxianggui** [bytefish/SpringBootMultiTenancy#1]
Hi, I learned your code, which is based on a Shared Schema.I would like to know if there is a practice based on discriminator.   

I have to use  discriminator-based multi-tenancy! You know, I have a tenant_id field for each table.

I know from [here](https://hibernate.atlassian.net/browse/HHH-6054)) that Hibernate doesn't have a practical solution for now, but I'm not sure if this issue has actually been turned off.

Looking forward to your reply. I really want to discuss it with someone.

**Comment by bytefish** [comment]
I would go for Row Level Security in PostgreSQL. Basically you create a User / Role per Tenant in the database. By setting policies on tables per row-level you can make sure, that a tenant is only allowed to read the subset.

Here is a nice writeup for PostgreSQL: 

* https://aws.amazon.com/blogs/database/multi-tenant-data-isolation-with-postgresql-row-level-security/

There is also an example for passing the Tenant using Postgres ``set_config`` feature. So RLS is what I would do in such a situation. I am sure other databases have similar features.

**Comment by bytefish** [comment]
It was interesting to see how it could be done. 

I have added an example project for the Shared Database, Shared Schema Multitenancy model here:

* https://github.com/bytefish/SpringBootMultitenancyUsingRowLevelSecurity

It uses the Postgres Row Level Security Feature for providing data isolation per tenant. 

There is also a blog post, that adds some more information.
