### ISSUE TITLE
Lookup db ...

### ISSUE THREAD

**Issue by somera** [bytefish/SpringBootMultiTenancy#2]
The solutions looks interesting. I'll take a closer look at it.

But there can be better "solution". The idea with sending header information about the database is not so good. You cann add a lookup db. there you can store which user is on which db. In this case you don't need send the right header information.

**Comment by bytefish** [comment]
Thanks for the idea! Yes this repository is just an example. There are a million different ways to pass the Tenant ID to the application. You could also pass it using a URL or set it in a JWT Token... A centralized user authentication might also work to resolve the Tenant ID.
